export const ORIGINAL_TEXT_CATALOG = [
  {
    appId: 'axion-ia-panel',
    env: 'prod',
    locale: 'pt-BR',
    items: [
      { namespace: 'home.hero', key: 'title', value: 'Controle total das operacoes AXION em um unico painel' },
      { namespace: 'home.hero', key: 'subtitle', value: 'Monitore apps, eventos e configuracoes em tempo real com governanca central.' },
      { namespace: 'home.hero', key: 'cta_primary', value: 'Abrir dashboard' },
      { namespace: 'home.hero', key: 'cta_secondary', value: 'Ver documentacao' },
      { namespace: 'home.metrics', key: 'kpi_events', value: 'Eventos monitorados' },
      { namespace: 'home.metrics', key: 'kpi_apps', value: 'Aplicacoes conectadas' },
    ],
  },
  {
    appId: 'axion-pay',
    env: 'prod',
    locale: 'pt-BR',
    items: [
      { namespace: 'home.hero', key: 'title', value: 'Receba pagamentos com velocidade, seguranca e controle' },
      { namespace: 'home.hero', key: 'subtitle', value: 'PIX, cartoes e conciliacao em uma experiencia simples para operacoes de alto volume.' },
      { namespace: 'home.hero', key: 'cta_primary', value: 'Criar conta' },
      { namespace: 'home.hero', key: 'cta_secondary', value: 'Falar com vendas' },
      { namespace: 'checkout', key: 'title', value: 'Finalize seu pagamento com seguranca' },
      { namespace: 'checkout', key: 'cta_pay', value: 'Pagar agora' },
    ],
  },
  {
    appId: 'axion-dev',
    env: 'prod',
    locale: 'pt-BR',
    items: [
      { namespace: 'home.hero', key: 'title', value: 'Tecnologia AXION para escalar operacoes digitais' },
      { namespace: 'home.hero', key: 'subtitle', value: 'Produtos, dados e automacao para acelerar crescimento com previsibilidade.' },
      { namespace: 'home.hero', key: 'cta_primary', value: 'Conhecer solucoes' },
      { namespace: 'home.hero', key: 'cta_secondary', value: 'Solicitar demo' },
      { namespace: 'home.sections', key: 'products_title', value: 'Produtos em destaque' },
      { namespace: 'home.sections', key: 'contact_title', value: 'Converse com o time AXION' },
    ],
  },
  {
    appId: 'axion-flow',
    env: 'prod',
    locale: 'pt-BR',
    items: [
      { namespace: 'home.hero', key: 'title', value: 'Fluxos inteligentes para vendas e operacoes' },
      { namespace: 'home.hero', key: 'subtitle', value: 'Orquestre processos, tarefas e squads com automacoes orientadas por dados.' },
      { namespace: 'home.hero', key: 'cta_primary', value: 'Iniciar fluxo' },
      { namespace: 'home.hero', key: 'cta_secondary', value: 'Explorar templates' },
      { namespace: 'home.modules', key: 'automation_title', value: 'Automacao operacional' },
      { namespace: 'home.modules', key: 'analytics_title', value: 'Analytics acionavel' },
    ],
  },
  {
    appId: 'axion-enterprise',
    env: 'prod',
    locale: 'pt-BR',
    items: [
      { namespace: 'home.hero', key: 'title', value: 'Plataforma enterprise para crescimento sustentavel' },
      { namespace: 'home.hero', key: 'subtitle', value: 'Centralize estrategia, marketing, vendas e dados em uma arquitetura escalavel.' },
      { namespace: 'home.hero', key: 'cta_primary', value: 'Falar com especialista' },
      { namespace: 'home.hero', key: 'cta_secondary', value: 'Ver casos de uso' },
      { namespace: 'home.trust', key: 'title', value: 'Confiado por operacoes de alta performance' },
      { namespace: 'home.trust', key: 'subtitle', value: 'Infra robusta com foco em disponibilidade, observabilidade e resultado.' },
    ],
  },
  {
    appId: 'axion-landing',
    env: 'prod',
    locale: 'pt-BR',
    items: [
      { namespace: 'home.hero', key: 'title', value: 'AXION: crescimento orientado por dados e execucao' },
      { namespace: 'home.hero', key: 'subtitle', value: 'Unimos estrategia, tecnologia e performance para escalar o seu negocio.' },
      { namespace: 'home.hero', key: 'cta_primary', value: 'Comecar agora' },
      { namespace: 'home.hero', key: 'cta_secondary', value: 'Ver solucoes' },
      { namespace: 'home.faq', key: 'title', value: 'Duvidas frequentes' },
      { namespace: 'home.contact', key: 'title', value: 'Vamos montar seu plano de crescimento' },
    ],
  },
  {
    appId: 'axion-ide',
    env: 'prod',
    locale: 'pt-BR',
    items: [
      { namespace: 'home.hero', key: 'title', value: 'Ambiente de desenvolvimento AXION para squads de alta entrega' },
      { namespace: 'home.hero', key: 'subtitle', value: 'Padronize pipelines, automacoes e experimentos com governanca tecnica.' },
      { namespace: 'home.hero', key: 'cta_primary', value: 'Abrir workspace' },
      { namespace: 'home.hero', key: 'cta_secondary', value: 'Ver guias' },
      { namespace: 'home.modules', key: 'title', value: 'Ferramentas para produtividade extrema' },
      { namespace: 'home.modules', key: 'subtitle', value: 'Do planejamento ao deploy em ciclos curtos e rastreaveis.' },
    ],
  },
  {
    appId: 'axion-hot-sales',
    env: 'prod',
    locale: 'pt-BR',
    items: [
      { namespace: 'home.hero', key: 'title', value: 'Campanhas de alta conversao com operacao enxuta' },
      { namespace: 'home.hero', key: 'subtitle', value: 'Ative ofertas, criativos e paginas com foco em receita e previsibilidade.' },
      { namespace: 'home.hero', key: 'cta_primary', value: 'Ativar campanha' },
      { namespace: 'home.hero', key: 'cta_secondary', value: 'Ver performance' },
      { namespace: 'home.sales', key: 'title', value: 'Motor de vendas em tempo real' },
      { namespace: 'home.sales', key: 'subtitle', value: 'Acompanhe funil, conversao e ROI por origem de trafego.' },
    ],
  },
  {
    appId: 'axion-agencia-hub',
    env: 'prod',
    locale: 'pt-BR',
    items: [
      { namespace: 'home.hero', key: 'title', value: 'Hub operacional para agencias orientadas a performance' },
      { namespace: 'home.hero', key: 'subtitle', value: 'Gerencie clientes, squads e resultados em um painel unico.' },
      { namespace: 'home.hero', key: 'cta_primary', value: 'Abrir hub' },
      { namespace: 'home.hero', key: 'cta_secondary', value: 'Adicionar cliente' },
      { namespace: 'home.modules', key: 'analytics_title', value: 'Analytics por cliente' },
      { namespace: 'home.modules', key: 'workflows_title', value: 'Workflows automatizados' },
    ],
  },
  {
    appId: 'axion-cloud',
    env: 'prod',
    locale: 'pt-BR',
    items: [
      { namespace: 'home.hero', key: 'title', value: 'Infraestrutura cloud para produtos digitais AXION' },
      { namespace: 'home.hero', key: 'subtitle', value: 'Escalabilidade, observabilidade e seguranca para cargas criticas.' },
      { namespace: 'home.hero', key: 'cta_primary', value: 'Provisionar ambiente' },
      { namespace: 'home.hero', key: 'cta_secondary', value: 'Ver status' },
      { namespace: 'home.modules', key: 'deploy_title', value: 'Deploy continuo' },
      { namespace: 'home.modules', key: 'monitoring_title', value: 'Monitoramento unificado' },
    ],
  },
];

